### PR TITLE
Don't override FantasyHex.

### PR DESCRIPTION
**Pull request by will-ca**
When I first found this tileset, I kinda liked it, but then promptly uninstalled it because it overrode FantasyHex and I still wanted to be able to switch between them at will.

So, this PR should make it not do that anymore:

image

Basically just renamed everything to "Pix5" instead of "FantasyHex", and then regenerated all atlases.

If there are any missing images after this, just copy them over from FantasyHex— Should be fine though, I think.

### CODE REVIEW

**Comment by AdityaMH** [comment]
From beginning i want to renaming from "FantasyHex" to "Pix5".

But my important reason why i won't do that because,
I want my "Civ Color StyleSheet ( https://github.com/AdityaMH/Civ-Army-Color-Style-Sheet )" work in both tileset (FantasyHex and Pix5 Tileset).

I will merge this if i can make my "CCS" work both without override.

**Comment by will-ca** [comment]
Okay, wow, that's pretty cool.

I had a look at the code and the wiki… https://github.com/yairm210/Unciv/pull/3231 apparently— It doesn't look like this feature is documented anywhere?

Anyway, I got the unit colours working in both FantasyHex and Pix5 from C.C.S. by just copying the "FantasyHex" folder and naming the copy to "Pix5" (or whatever you rename the Pix5 tileset to).

So you can rename Pix5 here, and then have the one C.C.S. mod supply two identical sets of files, one for FantasyHex and one for Pix5:

```
Civ Army Color Style Sheet/
├── game.atlas
├── game.png
├── Images
│   └── TileSets
│       ├── FantasyHex
│       │   ├── Railroad.png
│       │   ├── Road.png
│       │   └── Units
│       └── Pix5
│           ├── Railroad.png
│           ├── Road.png
│           └── Units
├── jsons
│   └── ModOptions.json
└── README.md
```

It looks like the whole mod is only a couple hundred KB, so the doubled download size should be fine. Unciv shouldn't be loading textures it won't use either, so increased (V)RAM use is either non-existent or not your fault.

**Comment by AdityaMH** [comment]
Okay, may be will be confused for add new unit.
ok i will merge later for testing.

anyway, what modOption.json used for?

**Comment by will-ca** [comment]
I would designate one folder as the only "real" one, and always work in there when adding new units, then just overwrite the other one with it when you're done.

AFAICT, `ModOptions.json` looks like it's automatically generated by Unciv using the metadata from Github.

Does my PR add it? It's a mistake if it does. After testing that this works, IMO you should close/revert the PR and then rename things yourself so mistakes from me like that won't slip in.

**Comment by AdityaMH** [comment]
I'm forgot.
another reason i won't do this because.
My tileset will not supported for RekMOD or other tileset.
why?, some tile only can showed if override FantasyHex

**Comment by will-ca** [comment]
> My tileset will not supported for RekMOD or other tileset.
> why?, some tile only can showed if override FantasyHex

…That shouldn't happen.

As long as your tileset has a named file for everything that the other mod needs, I think it should show.

What are the tiles that need to override FantasyHex to show? It can probably be fixed by copying and pasting the needed tiles from the mod. (Or maybe I'll PR fallback support into Unciv.)

**Comment by AdityaMH** [comment]
> It can probably be fixed by copying and pasting

I know that from beginning, but since i don't have pc.
It's hard enough to generate atlas and game.png

I want atlas and png generator, for android.
But kinda impossible.

**Comment by will-ca** [comment]
Right… Well, Unciv should probably try using FantasyHex as a fallback when it fails to find an image in the current TileSet.

**Comment by SomeTroglodyte** [comment]
> anyway, what modOption.json used for?

The [wiki doc](https://github.com/yairm210/Unciv/wiki/Miscellaneous-JSON-files#modoptionsjson) still looks OK to me...

**Comment by AdityaMH** [comment]
> > anyway, what modOption.json used for?
> 
> The [wiki doc](https://github.com/yairm210/Unciv/wiki/Miscellaneous-JSON-files#modoptionsjson) still looks OK to me...

I mean for tileset

**Comment by will-ca** [comment]
> > anyway, what modOption.json used for?
> 
> The [wiki doc](https://github.com/yairm210/Unciv/wiki/Miscellaneous-JSON-files#modoptionsjson) still looks OK to me...

Neat. Well, I'm glad I didn't try to PR a ModManifest.json in yet.

**Pull request merged**
